package com.knotworking.schmekels.feature.converter.domain.model

object CurrencyCatalog {

    val all: List<Currency> = listOf(
        Currency("AED", "United Arab Emirates Dirham", "د.إ"),
        Currency("AFN", "Afghan Afghani", "؋"),
        Currency("ALL", "Albanian Lek", "L"),
        Currency("AMD", "Armenian Dram", "֏"),
        Currency("ANG", "Netherlands Antillean Guilder", "ƒ"),
        Currency("AOA", "Angolan Kwanza", "Kz"),
        Currency("ARS", "Argentine Peso", "$"),
        Currency("AUD", "Australian Dollar", "$"),
        Currency("AWG", "Aruban Florin", "ƒ"),
        Currency("AZN", "Azerbaijani Manat", "₼"),
        Currency("BAM", "Bosnia-Herzegovina Convertible Mark", "KM"),
        Currency("BBD", "Barbadian Dollar", "$"),
        Currency("BDT", "Bangladeshi Taka", "৳"),
        Currency("BGN", "Bulgarian Lev", "лв"),
        Currency("BHD", "Bahraini Dinar", ".د.ب"),
        Currency("BIF", "Burundian Franc", "FBu"),
        Currency("BMD", "Bermudan Dollar", "$"),
        Currency("BND", "Brunei Dollar", "$"),
        Currency("BOB", "Bolivian Boliviano", "Bs."),
        Currency("BRL", "Brazilian Real", "R$"),
        Currency("BSD", "Bahamian Dollar", "$"),
        Currency("BTN", "Bhutanese Ngultrum", "Nu."),
        Currency("BWP", "Botswanan Pula", "P"),
        Currency("BYN", "Belarusian Ruble", "Br"),
        Currency("BZD", "Belize Dollar", "BZ$"),
        Currency("CAD", "Canadian Dollar", "$"),
        Currency("CDF", "Congolese Franc", "FC"),
        Currency("CHF", "Swiss Franc", "Fr"),
        Currency("CLP", "Chilean Peso", "$"),
        Currency("CNY", "Chinese Yuan", "¥"),
        Currency("COP", "Colombian Peso", "$"),
        Currency("CRC", "Costa Rican Colón", "₡"),
        Currency("CUP", "Cuban Peso", "$"),
        Currency("CVE", "Cape Verdean Escudo", "$"),
        Currency("CZK", "Czech Koruna", "Kč"),
        Currency("DJF", "Djiboutian Franc", "Fdj"),
        Currency("DKK", "Danish Krone", "kr"),
        Currency("DOP", "Dominican Peso", "RD$"),
        Currency("DZD", "Algerian Dinar", "د.ج"),
        Currency("EGP", "Egyptian Pound", "£"),
        Currency("ERN", "Eritrean Nakfa", "Nfk"),
        Currency("ETB", "Ethiopian Birr", "Br"),
        Currency("EUR", "Euro", "€"),
        Currency("FJD", "Fijian Dollar", "$"),
        Currency("FKP", "Falkland Islands Pound", "£"),
        Currency("GBP", "British Pound Sterling", "£"),
        Currency("GEL", "Georgian Lari", "₾"),
        Currency("GHS", "Ghanaian Cedi", "₵"),
        Currency("GIP", "Gibraltar Pound", "£"),
        Currency("GMD", "Gambian Dalasi", "D"),
        Currency("GNF", "Guinean Franc", "FG"),
        Currency("GTQ", "Guatemalan Quetzal", "Q"),
        Currency("GYD", "Guyanaese Dollar", "$"),
        Currency("HKD", "Hong Kong Dollar", "$"),
        Currency("HNL", "Honduran Lempira", "L"),
        Currency("HRK", "Croatian Kuna", "kn"),
        Currency("HTG", "Haitian Gourde", "G"),
        Currency("HUF", "Hungarian Forint", "Ft"),
        Currency("IDR", "Indonesian Rupiah", "Rp"),
        Currency("ILS", "Israeli New Shekel", "₪"),
        Currency("INR", "Indian Rupee", "₹"),
        Currency("IQD", "Iraqi Dinar", "ع.د"),
        Currency("IRR", "Iranian Rial", "﷼"),
        Currency("ISK", "Icelandic Króna", "kr"),
        Currency("JMD", "Jamaican Dollar", "J$"),
        Currency("JOD", "Jordanian Dinar", "د.ا"),
        Currency("JPY", "Japanese Yen", "¥"),
        Currency("KES", "Kenyan Shilling", "KSh"),
        Currency("KGS", "Kyrgystani Som", "с"),
        Currency("KHR", "Cambodian Riel", "៛"),
        Currency("KID", "Kiribati Dollar", "$"),
        Currency("KMF", "Comorian Franc", "CF"),
        Currency("KRW", "South Korean Won", "₩"),
        Currency("KWD", "Kuwaiti Dinar", "د.ك"),
        Currency("KYD", "Cayman Islands Dollar", "$"),
        Currency("KZT", "Kazakhstani Tenge", "₸"),
        Currency("LAK", "Laotian Kip", "₭"),
        Currency("LBP", "Lebanese Pound", "ل.ل"),
        Currency("LKR", "Sri Lankan Rupee", "Rs"),
        Currency("LRD", "Liberian Dollar", "$"),
        Currency("LSL", "Lesotho Loti", "L"),
        Currency("LYD", "Libyan Dinar", "ل.د"),
        Currency("MAD", "Moroccan Dirham", "د.م."),
        Currency("MDL", "Moldovan Leu", "L"),
        Currency("MGA", "Malagasy Ariary", "Ar"),
        Currency("MKD", "Macedonian Denar", "ден"),
        Currency("MMK", "Myanmar Kyat", "K"),
        Currency("MNT", "Mongolian Tugrik", "₮"),
        Currency("MOP", "Macanese Pataca", "MOP$"),
        Currency("MRU", "Mauritanian Ouguiya", "UM"),
        Currency("MUR", "Mauritian Rupee", "₨"),
        Currency("MVR", "Maldivian Rufiyaa", ".ރ"),
        Currency("MWK", "Malawian Kwacha", "MK"),
        Currency("MXN", "Mexican Peso", "$"),
        Currency("MYR", "Malaysian Ringgit", "RM"),
        Currency("MZN", "Mozambican Metical", "MT"),
        Currency("NAD", "Namibian Dollar", "$"),
        Currency("NGN", "Nigerian Naira", "₦"),
        Currency("NIO", "Nicaraguan Córdoba", "C$"),
        Currency("NOK", "Norwegian Krone", "kr"),
        Currency("NPR", "Nepalese Rupee", "₨"),
        Currency("NZD", "New Zealand Dollar", "$"),
        Currency("OMR", "Omani Rial", "ر.ع."),
        Currency("PAB", "Panamanian Balboa", "B/."),
        Currency("PEN", "Peruvian Sol", "S/"),
        Currency("PGK", "Papua New Guinean Kina", "K"),
        Currency("PHP", "Philippine Peso", "₱"),
        Currency("PKR", "Pakistani Rupee", "₨"),
        Currency("PLN", "Polish Złoty", "zł"),
        Currency("PYG", "Paraguayan Guarani", "₲"),
        Currency("QAR", "Qatari Rial", "ر.ق"),
        Currency("RON", "Romanian Leu", "lei"),
        Currency("RSD", "Serbian Dinar", "дин."),
        Currency("RUB", "Russian Ruble", "₽"),
        Currency("RWF", "Rwandan Franc", "FRw"),
        Currency("SAR", "Saudi Riyal", "ر.س"),
        Currency("SBD", "Solomon Islands Dollar", "$"),
        Currency("SCR", "Seychellois Rupee", "₨"),
        Currency("SDG", "Sudanese Pound", "ج.س."),
        Currency("SEK", "Swedish Krona", "kr"),
        Currency("SGD", "Singapore Dollar", "$"),
        Currency("SHP", "Saint Helena Pound", "£"),
        Currency("SLE", "Sierra Leonean Leone", "Le"),
        Currency("SLL", "Sierra Leonean Leone (old)", "Le"),
        Currency("SOS", "Somali Shilling", "S"),
        Currency("SRD", "Surinamese Dollar", "$"),
        Currency("SSP", "South Sudanese Pound", "£"),
        Currency("STN", "São Tomé and Príncipe Dobra", "Db"),
        Currency("SYP", "Syrian Pound", "£"),
        Currency("SZL", "Eswatini Lilangeni", "L"),
        Currency("THB", "Thai Baht", "฿"),
        Currency("TJS", "Tajikistani Somoni", "SM"),
        Currency("TMT", "Turkmenistani Manat", "m"),
        Currency("TND", "Tunisian Dinar", "د.ت"),
        Currency("TOP", "Tongan Paʻanga", "T$"),
        Currency("TRY", "Turkish Lira", "₺"),
        Currency("TTD", "Trinidad and Tobago Dollar", "TT$"),
        Currency("TVD", "Tuvaluan Dollar", "$"),
        Currency("TWD", "New Taiwan Dollar", "NT$"),
        Currency("TZS", "Tanzanian Shilling", "TSh"),
        Currency("UAH", "Ukrainian Hryvnia", "₴"),
        Currency("UGX", "Ugandan Shilling", "USh"),
        Currency("USD", "United States Dollar", "$"),
        Currency("UYU", "Uruguayan Peso", "\$U"),
        Currency("UZS", "Uzbekistani Som", "лв"),
        Currency("VES", "Venezuelan Bolívar", "Bs."),
        Currency("VND", "Vietnamese Dong", "₫"),
        Currency("VUV", "Vanuatu Vatu", "VT"),
        Currency("WST", "Samoan Tala", "WS$"),
        Currency("XAF", "Central African CFA Franc", "FCFA"),
        Currency("XCD", "East Caribbean Dollar", "$"),
        Currency("XDR", "Special Drawing Rights", "SDR"),
        Currency("XOF", "West African CFA Franc", "CFA"),
        Currency("XPF", "CFP Franc", "₣"),
        Currency("YER", "Yemeni Rial", "﷼"),
        Currency("ZAR", "South African Rand", "R"),
        Currency("ZMW", "Zambian Kwacha", "ZK"),
        Currency("ZWL", "Zimbabwean Dollar", "$")
    )

    val byCode: Map<String, Currency> = all.associateBy { it.code }

    operator fun get(code: String): Currency? = byCode[code]
}
